workflows:
  ios-native-build:
    name: iOS Native Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Resolve Swift Package Dependencies
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "unidorm.xcodeproj" \
            -scheme "unidorm" \
            -derivedDataPath derived_data
      - name: Build iOS App
        script: |
          xcodebuild build \
            -project "unidorm.xcodeproj" \
            -scheme "unidorm" \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath derived_data \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - derived_data/Build/Products/**/*.app